import { cpSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, URL } from 'node:url';

// plugin-react (not -swc): Vite 8 runs the React transform through Rolldown's
// Oxc pipeline, which is faster than the SWC plugin when no SWC plugins are used.
import react from '@vitejs/plugin-react';
// From 'vitest/config', not 'vite' — Vitest 4 no longer augments Vite's
// UserConfig type, so the `test` block only type-checks via this entry.
import { defineConfig } from 'vitest/config';

import { ROUTE_PATHS } from './src/config/routes';

/**
 * Writes a `_redirects` naming every real route.
 *
 * The obvious SPA rule is `/*  /index.html  200`, and it is a trap: it answers
 * 200 for ANY url, so a crawler that invents /a/b/c gets a page, finds more
 * invented links, and never terminates. Enumerating the routes means unknown
 * paths fall through to 404.html with a real 404, and crawling stops.
 *
 * Cloudflare Pages allows 2,000 static rules; this app uses about 35.
 */
function routeRedirects() {
  return {
    name: 'colony:route-redirects',
    apply: 'build' as const,
    closeBundle() {
      const rules = [
        '# Generated from src/config/routes.ts — do not edit by hand.',
        '#',
        '# Every real route is rewritten to the SPA shell. Anything not listed',
        '# here falls through to 404.html with a 404 status, which is what stops',
        '# a crawler from walking an infinite invented URL space.',
        '',
        ...ROUTE_PATHS.map((p) => `${p.padEnd(32)}/index.html   200`),
      ].join('\n');

      const out = fileURLToPath(new URL('./dist', import.meta.url));
      writeFileSync(join(out, '_redirects'), `${rules}\n`);

      // Generated alongside, because the demo needs one extra block and
      // Cloudflare Pages reads exactly one `_headers` file — a second file
      // beside it is silently ignored.
      const isDemo = process.env.VITE_ENABLE_MSW === 'true';
      const headers = [
        '# Generated by vite.config.ts — do not edit by hand.',
        '',
        '# Content-hashed, so the name changes whenever the bytes do.',
        '/assets/*',
        '  Cache-Control: public, max-age=31536000, immutable',
        '',
        '# Must never be cached, or a deploy never reaches anyone.',
        '/index.html',
        '  Cache-Control: no-cache',
        '',
        '/*',
        '  X-Content-Type-Options: nosniff',
        '  Referrer-Policy: strict-origin-when-cross-origin',
        '  X-Frame-Options: SAMEORIGIN',
        '  Permissions-Policy: camera=(), microphone=(), geolocation=()',
        ...(isDemo
          ? [
              // Belt and braces with robots.txt: this one binds the crawlers
              // that ignore robots.txt but do honour the header.
              '  X-Robots-Tag: noindex, nofollow',
            ]
          : []),
        '',
      ].join('\n');
      writeFileSync(join(out, '_headers'), headers);
    },
  };
}

/**
 * Copies demo-only static files into the build.
 *
 * They cannot live in `public/`, which Vite copies into every build. The demo's
 * robots.txt closes the whole site to crawlers — correct for a demo behind an
 * SPA fallback, and actively harmful in a real deployment, where it would
 * silently deindex the user's own app. Same for the MSW worker, which has no
 * business in a production bundle.
 */
function demoAssets() {
  return {
    name: 'colony:demo-assets',
    apply: 'build' as const,
    closeBundle() {
      if (process.env.VITE_ENABLE_MSW !== 'true') return;
      const from = fileURLToPath(new URL('./demo-public', import.meta.url));
      const to = fileURLToPath(new URL('./dist', import.meta.url));
      if (existsSync(from)) cpSync(from, to, { recursive: true });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), routeRedirects(), demoAssets()],

  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },

  server: {
    port: 5273,
    open: false,
  },

  preview: {
    port: 5274,
  },

  build: {
    target: 'es2022',
    sourcemap: false,
    // Surfaced in CI so bundle regressions fail loudly rather than drifting.
    chunkSizeWarningLimit: 900,
    rollupOptions: {
      output: {
        // Only React is pinned to a manual chunk: it is on the critical path
        // for every route and its hash should stay stable across releases.
        // antd and Recharts are deliberately NOT grouped — grouping them put
        // Recharts on the critical path for chart-less routes (measured:
        // Workplace pulled 1,610 kB with no chart on the page).
        manualChunks(id: string) {
          if (!id.includes('node_modules')) return;
          if (
            id.includes('/react/') ||
            id.includes('/react-dom/') ||
            id.includes('/scheduler/')
          ) {
            return 'react';
          }
          return;
        },
      },
    },
  },

  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    css: false,
    exclude: ['**/node_modules/**', '**/dist/**', './e2e/**'],
  },
});
