import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, URL } from 'node:url';

// plugin-react (not -swc): Vite 8 runs the React transform through Rolldown's
// Oxc pipeline, which is faster than the SWC plugin when no SWC plugins are used.
import react from '@vitejs/plugin-react';
// From 'vitest/config', not 'vite' — Vitest 4 no longer augments Vite's
// UserConfig type, so the `test` block only type-checks via this entry.
import { defineConfig } from 'vitest/config';

import { ROUTE_PATHS } from './src/config/routes';

/**
 * Emits a real index.html for every route.
 *
 * The usual SPA rule is `/*  /index.html  200`, and it is a trap: it answers
 * 200 for ANY url, so a crawler that invents /a/b/c gets a page, finds more
 * invented links, and never terminates. That shape ran up a four-figure bill on
 * another Colorlib demo in 2026.
 *
 * Rewriting only the real routes in `_redirects` looked like the fix and was
 * not: Cloudflare Pages canonicalises /index.html to /, so a rewrite pointing
 * there inherits the redirect and a deep link 308s to the root, losing the page
 * the visitor asked for.
 *
 * Writing the shell as a real file per route sidesteps both. Every real route is
 * genuine static content, so it is a plain 200; anything else has no file and
 * falls through to 404.html with a real 404, which is where crawling stops. It
 * needs no host-specific config either, so it behaves the same on Pages,
 * Netlify, S3 or nginx.
 *
 * `<route>.html` rather than `<route>/index.html`: static hosts serve the
 * former directly, while the latter earns a 308 to the trailing-slash form on
 * every deep link. Both work; only one costs a round trip.
 */
function routeShells() {
  return {
    name: 'colony:route-shells',
    apply: 'build' as const,
    closeBundle() {
      const out = fileURLToPath(new URL('./dist', import.meta.url));
      const shell = readFileSync(join(out, 'index.html'), 'utf8');

      for (const route of ROUTE_PATHS) {
        if (route === '/') continue; // already the root index.html
        const file = join(out, `${route.slice(1)}.html`);
        mkdirSync(dirname(file), { recursive: true });
        writeFileSync(file, shell);
      }

      const isDemo = process.env.VITE_ENABLE_MSW === 'true';
      const headers = [
        '# Generated by vite.config.ts — do not edit by hand.',
        '',
        '# Content-hashed, so the name changes whenever the bytes do.',
        '/assets/*',
        '  Cache-Control: public, max-age=31536000, immutable',
        '',
        '/*',
        '  X-Content-Type-Options: nosniff',
        '  Referrer-Policy: strict-origin-when-cross-origin',
        '  X-Frame-Options: SAMEORIGIN',
        '  Permissions-Policy: camera=(), microphone=(), geolocation=()',
        ...(isDemo
          ? [
              // Belt and braces with robots.txt: binds the crawlers that
              // ignore robots.txt but do honour the header.
              '  X-Robots-Tag: noindex, nofollow',
            ]
          : []),
        '',
      ].join('\n');
      writeFileSync(join(out, '_headers'), headers);
    },
  };
}

/**
 * Copies demo-only static files into the build.
 *
 * They cannot live in `public/`, which Vite copies into every build. The demo's
 * robots.txt closes the whole site to crawlers — correct for a demo behind an
 * SPA fallback, and actively harmful in a real deployment, where it would
 * silently deindex the user's own app. Same for the MSW worker, which has no
 * business in a production bundle.
 */
function demoAssets() {
  return {
    name: 'colony:demo-assets',
    apply: 'build' as const,
    closeBundle() {
      if (process.env.VITE_ENABLE_MSW !== 'true') return;
      const from = fileURLToPath(new URL('./demo-public', import.meta.url));
      const to = fileURLToPath(new URL('./dist', import.meta.url));
      if (existsSync(from)) cpSync(from, to, { recursive: true });
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), routeShells(), demoAssets()],

  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },

  server: {
    port: 5273,
    open: false,
  },

  preview: {
    port: 5274,
  },

  build: {
    target: 'es2022',
    sourcemap: false,
    // Surfaced in CI so bundle regressions fail loudly rather than drifting.
    chunkSizeWarningLimit: 900,
    rollupOptions: {
      output: {
        // Only React is pinned to a manual chunk: it is on the critical path
        // for every route and its hash should stay stable across releases.
        // antd and Recharts are deliberately NOT grouped — grouping them put
        // Recharts on the critical path for chart-less routes (measured:
        // Workplace pulled 1,610 kB with no chart on the page).
        manualChunks(id: string) {
          if (!id.includes('node_modules')) return;
          if (
            id.includes('/react/') ||
            id.includes('/react-dom/') ||
            id.includes('/scheduler/')
          ) {
            return 'react';
          }
          return;
        },
      },
    },
  },

  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    css: false,
    exclude: ['**/node_modules/**', '**/dist/**', './e2e/**'],
  },
});
